[theme]
#primaryColor="#D53D59"
#primaryColor="#f8f8f2"
#primaryColor="#1989C8"
#backgroundColor="#282a36"
#secondaryBackgroundColor="#44475a"
#textColor="#D53D59"
#textColor="#77D0B9"
#textColor="#FFDA00"
#textColor="#FFFF00"
#base="light"